src/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Arrested_suspect_s__c</fullName>
        <label>Arrested suspect(s)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Basis_for_Full_Search_Narrative__c</fullName>
        <label>Basis for Full Search Narrative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Basis_for_Full_Search__c</fullName>
        <label>Basis for Full Search</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admitted to weapon</fullName>
                </value>
                <value>
                    <fullName>Felt/observed object resembling weapon</fullName>
                </value>
                <value>
                    <fullName>Incident to arrest</fullName>
                </value>
                <value>
                    <fullName>Consent</fullName>
                </value>
                <value>
                    <fullName>Other (describe)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Basis_for_Pat_Down_Narrative__c</fullName>
        <label>Basis for Pat Down Narrative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Basis_for_Pat_Down__c</fullName>
        <label>Basis for Pat Down</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Verbal threats of violence</fullName>
                </value>
                <value>
                    <fullName>Knowledge of weapon/prior violence</fullName>
                </value>
                <value>
                    <fullName>Actions indicative of violence</fullName>
                </value>
                <value>
                    <fullName>Violent crime suspected</fullName>
                </value>
                <value>
                    <fullName>Suspicious bulge</fullName>
                </value>
                <value>
                    <fullName>Search incident to arrest</fullName>
                </value>
                <value>
                    <fullName>Suspicion of weapon (describe)</fullName>
                </value>
                <value>
                    <fullName>Other (describe)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Driver</fullName>
                </value>
                <value>
                    <fullName>Passenger</fullName>
                </value>
                <value>
                    <fullName>Pedestrian</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>District 1</fullName>
                </value>
                <value>
                    <fullName>District 2</fullName>
                </value>
                <value>
                    <fullName>District 3</fullName>
                </value>
                <value>
                    <fullName>District 4</fullName>
                </value>
                <value>
                    <fullName>District 5</fullName>
                </value>
                <value>
                    <fullName>District 6</fullName>
                </value>
                <value>
                    <fullName>District 7</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duration_of_Contact__c</fullName>
        <label>Duration of Contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>&lt;5 Min</fullName>
                </value>
                <value>
                    <fullName>5-9 Min</fullName>
                </value>
                <value>
                    <fullName>10-19 Min</fullName>
                </value>
                <value>
                    <fullName>20-29 Min</fullName>
                </value>
                <value>
                    <fullName>30-39 Min</fullName>
                </value>
                <value>
                    <fullName>40-49 Min</fullName>
                </value>
                <value>
                    <fullName>50-59 Min</fullName>
                </value>
                <value>
                    <fullName>&gt;60 Min</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Foot_Pursuit__c</fullName>
        <label>Foot Pursuit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Search__c</fullName>
        <label>Full Search</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Incident_Date_Time__c</fullName>
        <label>Incident Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Issued_Summons__c</fullName>
        <label>Issued Summons</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Num_Officers_Involved__c</fullName>
        <label># Officers Involved</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>&gt;5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Num_of_Subjects__c</fullName>
        <label># of Subjects</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>&gt;5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Observation_Notes__c</fullName>
        <label>Observation Notes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Officer_Badge_Number__c</fullName>
        <label>Officer Badge Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Officer_in_Uniform__c</fullName>
        <label>Officer in Uniform</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pat_Down__c</fullName>
        <label>Pat Down</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_Narrative__c</fullName>
        <label>Reason Narrative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Traffic Violation</fullName>
                </value>
                <value>
                    <fullName>Equipment Violation</fullName>
                </value>
                <value>
                    <fullName>Casing a victim or location</fullName>
                </value>
                <value>
                    <fullName>Actions indicative of a drug transaction</fullName>
                </value>
                <value>
                    <fullName>Actions of engaging in a violent crime</fullName>
                </value>
                <value>
                    <fullName>Fits description of a suspect</fullName>
                </value>
                <value>
                    <fullName>Proximity to reported crime location</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Siezed_Contraband__c</fullName>
        <label>Seized Contraband</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Contraband__c</fullName>
        <label>Type of Contraband</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Narcotics</fullName>
                </value>
                <value>
                    <fullName>Firearm</fullName>
                </value>
                <value>
                    <fullName>Other Weapon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vehicle_Pursuit__c</fullName>
        <label>Vehicle Pursuit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Incident</label>
    <nameField>
        <displayFormat>ICD-{00000000}</displayFormat>
        <label>Incident Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Incident_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Age_Group__c</fullName>
        <label>Age Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>9 and under</fullName>
                </value>
                <value>
                    <fullName>10-16</fullName>
                </value>
                <value>
                    <fullName>17-21</fullName>
                </value>
                <value>
                    <fullName>22-30</fullName>
                </value>
                <value>
                    <fullName>31-45</fullName>
                </value>
                <value>
                    <fullName>45-60</fullName>
                </value>
                <value>
                    <fullName>61 and over</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Incident Contacts</relationshipLabel>
        <relationshipName>Incident_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Incident Contact</label>
    <nameField>
        <displayFormat>CT-{00000000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incident Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PSPoliceContactCardController.cls
public class PSPoliceContactCardController
{
  @AuraEnabled
  public static String dummy()
  {
    System.debug('dummy invoked...');

    return '';
  }

  @AuraEnabled
  public static String reverseGeocodeEsri(Decimal lat, Decimal lng)
  {
    System.debug('reverseGeocodeEsri invoked...');

    return PSGeoUtils.reverseGeocodeEsri(lat, lng);
  }

  @AuraEnabled
  public static String getUserBadgeNumber()
  {
    System.debug('getUserBadgeNumber invoked...');

    Id userId = UserInfo.getUserId();

    if (userId != null)
    {
      User u = [SELECT Badge_Number__c FROM User WHERE Id = :userId];
      return u.Badge_Number__c;
    }
    else
    {
      return '';
    }

  }


  @AuraEnabled
  public static String geocodeEsri(String addr)
  {
    System.debug('geocodeEsri invoked...');

    return PSGeoUtils.geocodeEsri(addr);
  }

  @AuraEnabled
  public static List<String> getCarYears()
  {
    System.debug('getCarYears invoked...');

    return PSCarQueryUtils.getYears();
  }

  @AuraEnabled
  public static List<String> getCarMakes(Integer year)
  {
    System.debug('getCarMakes invoked...');

    return PSCarQueryUtils.getMakes(year);
  }

  @AuraEnabled
  public static List<String>  getCarModels(Integer year, String make)
  {
    System.debug('getCarModels invoked...');

    return PSCarQueryUtils.getModels(year, make);
  }

  @AuraEnabled
  public static String getDistrict(Decimal lat, Decimal lng)
  {
    System.debug('getDistrict invoked...');

    return PSDenverDistrictUtils.retrieveDistrict(lat, lng);
  }

  @AuraEnabled
  public static String getPicklistValues(String objType)
  {
    System.debug('getPicklistValues invoked...');

    return PSMetaUtils.getObjectPicklists(objType);
  }

  @AuraEnabled
  public static String loadIncidentRecord(String recordId)
  {
    System.debug('loadIncidentRecord invoked...');
    PSResponse resp = new PSResponse();

    try
    {
      /////////////////////////////
      // get the Incident record //
      /////////////////////////////
      Incident__c inc = [SELECT Id, Num_of_Subjects__c, Num_Officers_Involved__c, Address__c,
                         Arrested_suspect_s__c, Basis_for_Full_Search__c, Basis_for_Full_Search_Narrative__c,
                         Basis_for_Pat_Down__c, Basis_for_Pat_Down_Narrative__c, Contact_Type__c, District__c,
                         Duration_of_Contact__c, Foot_Pursuit__c, Full_Search__c, Incident_Date_Time__c, Name,
                         Issued_Summons__c, Location__Latitude__s, Location__Longitude__s, Officer_Badge_Number__c,
                         Officer_in_Uniform__c, Pat_Down__c, Reason__c, Reason_Narrative__c, Siezed_Contraband__c,
                         Type_of_Contraband__c, Vehicle_Pursuit__c, Observation_Notes__c
                         FROM Incident__c
                         WHERE Id = :recordId];

      Map<String, Object>respMap = new Map<String, Object>();
      respMap.put('incident', inc);

      //////////////////////////////////////////////
      // load associated Incident Contact records //
      //////////////////////////////////////////////
      List<Incident_Contact__c> incContacts = [SELECT Id, Name, Age_Group__c, Gang_Affiliation__c, Gender__c,
                                Person_Num__c, Race_Ethnicity__c, Vehicle_Year__c,
                                Vehicle_Make__c, Vehicle_Model__c
                                FROM Incident_Contact__c
                                WHERE Incident__c = :recordId
                                    ORDER BY Name ASC];

      respMap.put('incidentContacts', incContacts);

      ///////////////////////////////
      // load and file attachments //
      ///////////////////////////////
      List<String> fileList = new List<String>();
      List<ContentDocumentLink> cdList = [SELECT ContentDocumentId, Id, IsDeleted, LinkedEntityId, ShareType, SystemModstamp, Visibility
                                          FROM ContentDocumentLink
                                          WHERE linkedentityid = :recordId];
      if (cdList != null)
      {
        for (ContentDocumentLink cdl : cdList)
        {
          fileList.add(cdl.ContentDocumentId);
        }
      }

      respMap.put('incidentFiles', fileList);

      resp.data = respMap;

    }
    catch (exception e)
    {
      resp.status = PSResponse.ERROR;
      resp.msg = e.getMessage();
    }

    return  JSON.serialize(resp);
  }

  @AuraEnabled
  public static String upsertIncidentAndContacts(String params)
  {
    System.debug('upsertIncidentAndContacts invoked...');
    Map<String, String> paramMap = (Map<String, String>)JSON.deserialize(params,   Map<String, String>.class);

    PSResponse resp = new PSResponse();

    try
    {
      //System.debug('incident=' + paramMap.get('incident'));
      //System.debug('incidentContacts=' + paramMap.get('incidentContacts'));
      Incident__c incident = (Incident__c)JSON.deserialize(paramMap.get('incident'), Incident__c.class);
      List<Incident_Contact__c> incidentContacts = (List<Incident_Contact__c>)JSON.deserialize(paramMap.get('incidentContacts'), List<Incident_Contact__c>.class);

      ////////////////////////
      // store the incident //
      ////////////////////////
      if (incident.id == null)
      {
        insert incident;
      }
      else
      {
        update incident;
      }

      /////////////////////////////////
      // store the incident contacts //
      /////////////////////////////////
      if (incidentContacts != null && incidentContacts.size() > 0)
      {
        for (Incident_Contact__c ic : incidentContacts)
        {
          if (ic.Id == null)
          {
            ic.Incident__c = incident.Id;
            insert ic;
          }
          else
          {
            update ic;
          }
        }
      }

      Map<String, Object>respMap = new Map<String, Object>();
      respMap.put('incident', incident);
      respMap.put('incidentContacts', incidentContacts);
      //respMap.put('transactionMsg', payResp.getMessage());

      resp.data = respMap;

    }
    catch (exception e)
    {
      resp.status = PSResponse.ERROR;
      resp.msg = e.getMessage();
    }

    return  JSON.serialize(resp);

  }


}